# Instructions/Readme for grader- 
1. This file contains code for various analyses/segments including player count, gender demographics, purchasing behavior, top selling, top profitable items, etc.
2. I have provided print comments for you to check each step(if needed). You might just have to uncomment or comment the print commands. They are all commented right now.
3. The outputs are indexed with respect to the groups as per the assignment request and I have tried my best to format and present the way as shown in the example analyses sheet that was provided along with the assignment.
4. I'm including a synopsis of trends-"Heroes Of Pymoli Data Analysis Trends & Insights" in the beginning as well as in the end.


# Heroes Of Pymoli Data Analysis Trends & Insights-

#1. Customer Trends- 
---> Of the 576 active players, the vast majority are male (84.03%). There also exists, a smaller, but notable proportion of female players (14.06%). 
---> Our peak age demographic falls between 20-24 (44.79%) with secondary groups falling between 15-19 (18.58%) and 25-29 (13.37%).

#2. Product Trends- 
---> 183 unique items, priced at an average of  $3.05, were sold, generating a total revenue of $2379.77 
---> "Oathbreaker, Last Hope of the Breaking Storm" (Item 178) is the highest selling item generating the highest total purchase revenue of  50.76 followed by Nirvana (Item ID#82); generating total purchase revenue of 44.10

#3. Purchase Transaction Trends- 
---> We saw 780 total purchases leading to a total revenue of  2379.77andaveragepurchasepriceof 4.13 per user. 
---> User- "isosia93"is the most purchased customer making the higest total purchase value of $18.96

In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np

# File to Load (Remember to Change These)
file_to_load = "Resources/purchase_data.csv"

# Read Purchasing File and store into Pandas data frame

df = pd.read_csv(file_to_load)

df.count()
df.dtypes
df.head()


Purchase ID             SN  Age Gender  Item ID  \
0            0        Lisim78   20   Male      108   
1            1    Lisovynya38   40   Male      143   
2            2     Ithergue48   24   Male       92   
3            3  Chamassasya86   24   Male      100   
4            4      Iskosia90   23   Male      131   

                                   Item Name  Price  
0  Extraction, Quickblade Of Trembling Hands   3.53  
1                          Frenzied Scimitar   1.56  
2                               Final Critic   4.88  
3                                Blindscythe   3.27  
4                                       Fury   1.44

## Player Count

* Display the total number of players


In [20]:
# ------Players Count------
# determining total players
players_count= df['SN'].nunique()

total_players=pd.DataFrame({"Total number of Players": [players_count]})


print(total_players.head())





   Total number of Players
0                      576


## Purchasing Analysis (Total)

* Run basic calculations to obtain number of unique items, average price, etc.


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame


In [19]:
# ------Purchasing Analysis(Total)------

print("-----------Purchasing Analysis(Total)-----------")
# Determining number of unique items
unique_items_count= df['Item ID'].nunique()
#print(unique_items_count)

# Determining total revenue
total_revenue= df['Price'].sum()
#print(total_revenue)

# Determining Number of Purchases
total_purchases= df['Purchase ID'].count()
#print(total_purchases)

# Determining Average Price
average_price= df['Price'].mean()
#print(average_price)

purchasing_summary= pd.DataFrame({"Number of Unique Items": [unique_items_count],
                           "Average Price": [average_price],
                           "Number of Purchases": [total_purchases],
                           "Total Revenue": [total_revenue]})

purchasing_summary["Average Price"] = purchasing_summary["Average Price"].map("${:.2f}".format)
purchasing_summary["Total Revenue"] = purchasing_summary["Total Revenue"].map("${:.2f}".format)
print(purchasing_summary)

   Number of Unique Items Average Price  Number of Purchases Total Revenue
0                     183         $3.05                  780      $2379.77



## Gender Demographics

* Percentage and Count of Male Players


* Percentage and Count of Female Players


* Percentage and Count of Other / Non-Disclosed




In [14]:
# ------Gender Demographics------
print("--------Gender Demographics-----------")



# Grouping Dataframe by Gender
customer_group= df.groupby("Gender")

# Determining the Total Count of players series under each gender group
gender=customer_group["SN"].nunique()
gender= gender.rename(columns={"Gender":"Gender","SN": "Total Count"})


# Determing percentage of players series under each gender group
gender_percentage= (customer_group["SN"].nunique()/players_count)*100
gender_percentage= gender_percentage.rename(columns={"Gender":"Gender","Purchase ID": "Percentage of Players"})


# Forming a dataframe from total count series and percentage series and renaming column names and formating column values
gender_df= pd.concat([gender,gender_percentage],axis=1).reset_index()
gender_df= gender_df.rename(columns={"Gender": "Gender", 0: "Total Count", 1: "Percentage of Players"})
gender_df["Percentage of Players"] = gender_df["Percentage of Players"].map("{:.2f}".format)

#Sorting table by Total Count values and setting index to Gender and formatting percentage column
gender_df=gender_df.sort_values('Total Count',axis=0, ascending= False)
gender_df=gender_df.set_index("Gender")


print(gender_df.head())







--------Gender Demographics-----------
                       Total Count Percentage of Players
Gender                                                  
Male                           484                 84.03
Female                          81                 14.06
Other / Non-Disclosed           11                  1.91



## Purchasing Analysis (Gender)

* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender




* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [31]:
#--------- Purchasing Analysis (Gender)----------------

print("--------- Purchasing Analysis (Gender)----------------")

# Setting a new Dataframe column with index of unique integers assigned to each purchase id called as customer id
mapping = {k: v for v, k in enumerate(df.SN.unique())}
df['Customer ID'] = df.SN.map(mapping)
new_df= df.set_index('Customer ID')


# Grouping by gender and determining purchase count series per gender
gender_group=df.groupby("Gender")
purchase_count=gender_group["Purchase ID"].count()


# Determining average purchase price series per gender group
average_pur_pr=gender_group["Price"].mean()
#average_pur_pr= average_pur_pr.rename(columns={"Gender":"Gender","Price": "Average Purchase Price"})
#print(average_pur_pr)



# Determining total purchase value series per gender group
total_pur_value=gender_group["Price"].sum()
total_pur_value= total_pur_value.rename(columns={"Gender":"Gender","Price": "Total Purchase Value"})
#print(total_pur_value)



# Determining Avg Total Purchase per Person series per gender group
avg_total_pur_per=customer_group["Price"].sum()/gender_group["Customer ID"].nunique()
avg_total_pur_per= avg_total_pur_per.rename(columns={"Gender":"Gender",1: "Average Total Purchase Per Person"})
#print(avg_total_pur_per)


# Make a dataframe from all the series to display analysis
new_df=pd.concat([gender,purchase_count,average_pur_pr,total_pur_value,avg_total_pur_per],axis=1).reset_index()

# Renaming the columns and formatting column values of the new dataframe
new_df= new_df.rename(columns={"Gender": "Gender", 0: "Unique Customer Count", "Purchase ID": "Purchase Count", "Price":  "Average Purchase Price",1: "Total Purchase Value", 2: "Average Total Purchase Per Person"})
new_df= new_df[["Gender","Purchase Count", "Average Purchase Price", "Total Purchase Value", "Average Total Purchase Per Person"]]
new_df["Average Purchase Price"] = new_df["Average Purchase Price"].map("${:.2f}".format)
new_df["Total Purchase Value"] = new_df["Total Purchase Value"].map("${:.2f}".format)
new_df["Average Total Purchase Per Person"] = new_df["Average Total Purchase Per Person"].map("${:.2f}".format)

# Setting new dataframe index to Gender
new_df=new_df.set_index("Gender")

print(new_df.head())





--------- Purchasing Analysis (Gender)----------------
                       Purchase Count Average Purchase Price  \
Gender                                                         
Female                            113                  $3.20   
Male                              652                  $3.02   
Other / Non-Disclosed              15                  $3.35   

                      Total Purchase Value Average Total Purchase Per Person  
Gender                                                                        
Female                             $361.94                             $4.47  
Male                              $1967.64                             $4.07  
Other / Non-Disclosed               $50.19                             $4.56  


## Age Demographics

* Establish bins for ages


* Categorize the existing players using the age bins. Hint: use pd.cut()


* Calculate the numbers and percentages by age group


* Create a summary data frame to hold the results


* Optional: round the percentage column to two decimal points


* Display Age Demographics Table


In [36]:
#----------Age Demographics--------------------
print("----------Age Demographics--------------------")

# Establish bins for ages
bins = [0, 9, 14, 19, 24, 29, 34, 39, 45]

# Create the names for the four bins
group_labels = ["<10", "10-14", "15-19", "20-24", "25-29","30-34","35-39","40+"]


df["Age Group"] = pd.cut(df["Age"], bins, labels = group_labels)


# Create a Groupby object based upon "Age Group"
age_group= df.groupby("Age Group")

# Determining total count series per age group
age_group_count= age_group["Customer ID"].nunique()
age_group_count= age_group_count.rename(columns={"Age Group":"Age Group","Customer ID": "Total Count"})
#print(age_group_count)

# Determining Percentage of Players series per age group
age_group_percentage= ((age_group["Customer ID"].nunique())/(df["Customer ID"].nunique())*100)
age_group_percentage= age_group_percentage.rename(columns={"Age Group":"Age Group","Customer ID": "Percentage of Players"})
#print(age_group_percentage)

# Forming a Dataframe table from above series and renaming/formatting columns
age_df=pd.concat([age_group_count,age_group_percentage],axis=1).reset_index()
age_df= age_df.rename(columns={"Age Group": "Age Group", 0: "Total Count", 1: "Percentage of Players"})
age_df["Percentage of Players"] = age_df["Percentage of Players"].map("{:.2f}".format)

# Setting dataframe index to Gender
age_df=age_df.set_index("Age Group")
print(age_df.head())



----------Age Demographics--------------------
           Total Count Percentage of Players
Age Group                                   
<10                 17                  2.95
10-14               22                  3.82
15-19              107                 18.58
20-24              258                 44.79
25-29               77                 13.37


## Purchasing Analysis (Age)

* Bin the purchase_data data frame by age


* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [38]:
#-------Purchasing Analysis(Age)---------------

print("-------Purchasing Analysis(Age)---------------")

# Determine Purchase Count per age group
age_group_pur_count= age_group["Purchase ID"].nunique()
age_group_pur_count= age_group_pur_count.rename(columns={"Age Group":"Age Group","Purchase ID": "Purchase Count"})
#print(age_group_pur_count)

# Determine Average Purchase Price per age group
age_group_avg_pur_pr= age_group["Price"].mean()
age_group_avg_pur_pr= age_group_avg_pur_pr.rename(columns={"Age Group":"Age Group","Price": "Average Purchase Price"})
#print(age_group_avg_pur_pr)

# Determine Total Purchase Value per age group
age_group_tot_pur_value= age_group["Price"].sum()
age_group_tot_pur_value= age_group_tot_pur_value.rename(columns={"Age Group":"Age Group","Price": "Total Purchase Value"})
#print(age_group_tot_pur_value)

# Determine Avg Total Purchase per Person per age group
age_group_avg_tot_pur_pr= (age_group["Price"].sum())/(age_group["Customer ID"].nunique())
age_group_avg_tot_pur_pr= age_group_avg_tot_pur_pr.rename(columns={"Age Group":"Age Group","Price": "Avg Total Purchase per Person"})
#print(age_group_avg_tot_pur_pr)


# Forming a Dataframe table from above series and renaming/formatting columns
age_rev_df=pd.concat([age_group_pur_count,age_group_avg_pur_pr,age_group_tot_pur_value,age_group_avg_tot_pur_pr],axis=1).reset_index()
age_rev_df= age_rev_df.rename(columns={"Age Group": "Age Group", 0: "Purchase Count", 1: "Average Purchase Price",2: "Total Purchase Value", 3: "Avg Total Purchase per Person" })
age_rev_df["Average Purchase Price"] = age_rev_df["Average Purchase Price"].map("${:.2f}".format)
age_rev_df["Total Purchase Value"] = age_rev_df["Total Purchase Value"].map("${:.2f}".format)
age_rev_df["Avg Total Purchase per Person"] = age_rev_df["Avg Total Purchase per Person"].map("${:.2f}".format)

# Setting index of new dataframe to "Age Group"
age_rev_df=age_rev_df.set_index("Age Group")
print(age_rev_df.head())



-------Purchasing Analysis(Age)---------------
           Purchase Count Average Purchase Price Total Purchase Value  \
Age Group                                                               
<10                    23                  $3.35               $77.13   
10-14                  28                  $2.96               $82.78   
15-19                 136                  $3.04              $412.89   
20-24                 365                  $3.05             $1114.06   
25-29                 101                  $2.90              $293.00   

          Avg Total Purchase per Person  
Age Group                                
<10                               $4.54  
10-14                             $3.76  
15-19                             $3.86  
20-24                             $4.32  
25-29                             $3.81  


## Top Spenders

* Run basic calculations to obtain the results in the table below


* Create a summary data frame to hold the results


* Sort the total purchase value column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame



In [45]:
#--------------------Top Spenders---------------------
print("--------------------Top Spenders---------------------")

# Grouping initial Dataframe by SN
spenders_group= df.groupby("SN")
#print(type(spenders_group))

# Determining the purchase count series for each SN
spenders_group_count= spenders_group["Purchase ID"].count()
spenders_group_count= spenders_group_count.rename(columns={"SN":"SN","Purchase ID": "Purchase Count"})
#print(spenders_group_count)

# Determining the Average Purchase Price series for each SN
spenders_group_avg_pur_pr= spenders_group["Price"].mean()
spenders_group_avg_pur_pr= spenders_group_avg_pur_pr.rename(columns={"SN":"SN","Price": "Average Purchase Price"})
#print(spenders_group_avg_pur_pr)

# Determining the Total Purchase Value series for each SN
spenders_group_tot_pur_value= spenders_group["Price"].sum()
spenders_group_tot_pur_value= spenders_group_tot_pur_value.rename(columns={"SN":"SN","Price": "Total Purchase Value"})
#print(spenders_group_tot_pur_value)

# Forming the top spenders dataframe using above data series; sorting the dataframe in descending values of total purchase value and formating/renaming columns
top_spenders_df=pd.concat([spenders_group_count,spenders_group_avg_pur_pr,spenders_group_tot_pur_value],axis=1).reset_index()
top_spenders_df=top_spenders_df.sort_values(2, axis=0, ascending=False)
top_spenders_df= top_spenders_df.rename(columns={"SN": "SN", 0: "Purchase Count", 1: "Average Purchase Price",2: "Total Purchase Value" })
top_spenders_df["Average Purchase Price"] = top_spenders_df["Average Purchase Price"].map("${:.2f}".format)
top_spenders_df["Total Purchase Value"] = top_spenders_df["Total Purchase Value"].map("${:.2f}".format)

# Setting index of new dataframe to "SN"
top_spenders_df=top_spenders_df.set_index("SN")

print(top_spenders_df.head())


--------------------Top Spenders---------------------
             Purchase Count Average Purchase Price Total Purchase Value
SN                                                                     
Lisosia93                 5                  $3.79               $18.96
Idastidru52               4                  $3.86               $15.45
Chamjask73                3                  $4.61               $13.83
Iral74                    4                  $3.40               $13.62
Iskadarya95               3                  $4.37               $13.10


## Most Popular Items

* Retrieve the Item ID, Item Name, and Item Price columns


* Group by Item ID and Item Name. Perform calculations to obtain purchase count, item price, and total purchase value


* Create a summary data frame to hold the results


* Sort the purchase count column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame



In [46]:
#--------------------Most Popular Items---------------------
print("--------------------Most Popular Items---------------------")

# Grouping the dataframe by Item ID

item_group= df.groupby("Item ID")

# Determining Purchase count series for each item in the item group and assigning a column name
item_group_count_series= item_group['Purchase ID'].count()
item_group_count_series= item_group_count_series.rename(columns={"Item ID":"Item ID","Purchase ID": "Purchase Count"})
#print(item_group_count_series)
#print(type(item_group_count_series))

# Determining Item Price series for each item in the item group and assigning a column name
item_group_price= item_group["Price"].mean()
item_group_price= item_group_price.rename(columns={"Item ID":"Item ID","Price": "Item Price"})


# Determining Total Purchase Value series for each item in the item group and assigning a column name
item_group_total_purchase_value= item_group["Price"].sum()
item_group_total_purchase_value= item_group_total_purchase_value.rename(columns={"Item ID":"Item ID","Price": "Total Purchase Value"})


# Organizing a new Dataframe with only two columns Item names and IDs and setting index to Item ID
item_name_df= df[["Item ID","Item Name"]]
item_name_df= (df[["Item ID","Item Name"]]).set_index("Item ID")
#print(organized_df.head())

# Formulating a dataframe from Item ID, purchase count, item price and total purchase value and renaming columns of the new dataframe
top_items_df=pd.concat([item_group_count_series,item_group_price,item_group_total_purchase_value],axis=1)
top_items_df= top_items_df.rename(columns={"Item ID": "Item ID", 0: "Purchase Count", 1: "Item Price",2: "Total Purchase Value" })
#print(top_items_df.head())

# Merging item_name dataframe and grouped dataframe and removing duplicate rows
organized_df= pd.merge(top_items_df,item_name_df, on="Item ID",how='left')
#print(organized_df.head())
organized_df=organized_df.drop_duplicates(subset=['Item Price', 'Total Purchase Value', 'Item Name'])
#print(new_df.columns)

# Formating organized df columns to $ and upto 2 decimals
organized_df=organized_df[["Item Name","Purchase Count", "Item Price", "Total Purchase Value"]]
#print(organized_df.head())
organized_df["Item Price"] = organized_df["Item Price"].map("${:.2f}".format)
organized_df["Total Purchase Value"] = organized_df["Total Purchase Value"].map("${:.2f}".format)

# Sorting organized dataframe in descending values of purchase count
popular_df=organized_df.sort_values("Purchase Count", axis=0, ascending=False)
print(popular_df.head())




--------------------Most Popular Items---------------------
                                            Item Name  Purchase Count  \
Item ID                                                                 
178      Oathbreaker, Last Hope of the Breaking Storm              12   
145                              Fiery Glass Crusader               9   
108         Extraction, Quickblade Of Trembling Hands               9   
82                                            Nirvana               9   
19                      Pursuit, Cudgel of Necromancy               8   

        Item Price Total Purchase Value  
Item ID                                  
178          $4.23               $50.76  
145          $4.58               $41.22  
108          $3.53               $31.77  
82           $4.90               $44.10  
19           $1.02                $8.16  


## Most Profitable Items

* Sort the above table by total purchase value in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the data frame



In [47]:
#--------------------Most Profitable Items---------------------
print("--------------------Most Profitable Items---------------------")

# Forming a new dataframe that sorts "top_items_df" according to descending values of total purchase value
top_items_purchases_df=top_items_df.sort_values('Total Purchase Value',ascending=False)


# Merging top_items_purchases_df and item_name_df to generate item name column
new_df=pd.merge(top_items_purchases_df,item_name_df, on="Item ID",how='left')

# Removing duplicate entries of item IDs but keeping the first entry
new_df=new_df.drop_duplicates(subset=['Item Price', 'Total Purchase Value', 'Item Name'])

# Reaaranging the columns post merge
new_df=new_df[["Item Name","Purchase Count", "Item Price", "Total Purchase Value"]]
print(new_df.head())



--------------------Most Profitable Items---------------------
                                            Item Name  Purchase Count  \
Item ID                                                                 
178      Oathbreaker, Last Hope of the Breaking Storm              12   
82                                            Nirvana               9   
145                              Fiery Glass Crusader               9   
92                                       Final Critic               8   
103                                    Singed Scalpel               8   

         Item Price  Total Purchase Value  
Item ID                                    
178            4.23                 50.76  
82             4.90                 44.10  
145            4.58                 41.22  
92             4.88                 39.04  
103            4.35                 34.80  


# Heroes Of Pymoli Data Analysis Trends & Insights-

1. Customer Trends- 
---> Of the 576 active players, the vast majority are male (84.03%). There also exists, a smaller, but notable proportion of female players (14.06%). 
---> Our peak age demographic falls between 20-24 (44.79%) with secondary groups falling between 15-19 (18.58%) and 25-29 (13.37%).

2. Product Trends- 
---> 183 unique items, priced at an average of  $3.05, were sold, generating a total revenue of $2379.77 
---> "Oathbreaker, Last Hope of the Breaking Storm" (Item 178) is the highest selling item generating the highest total purchase revenue of  50.76 followed by Nirvana (Item ID#82); generating total purchase revenue of 44.10

3. Purchase Transaction Trends- 
---> We saw 780 total purchases leading to a total revenue of  2379.77andaveragepurchasepriceof 4.13 per user. 
---> User- "isosia93"is the most purchased customer making the higest total purchase value of $18.96